### ISSUE TITLE
Says colorPicker is not a function

### ISSUE THREAD

**Issue by michaelsboost** [replit/Codemirror-CSS-color-picker#10]
Using rollup for bundling. 

How can I use this with just vanilla js and rollup?

![20230302_191103.jpg](https://user-images.githubusercontent.com/2473707/222606580-5aba7d2d-194e-4915-b264-033aa2d0fab6.jpg)

**Comment by masad-frost** [comment]
I'm not sure. We export both cjs and esm module, and both seem to have the correct output. You can verify here https://www.unpkg.com/browse/@replit/codemirror-css-color-picker@6.0.0/dist/, don't see anything wrong. You probably need to configure rollup correctly. I recommend using vite or parcel, they take care of things more, rollup is too low level.
